export const freezerOptions = [
  { value: '0', label: 'Which freezer?' },
  { value: '1', label: 'Kitchen' },
  { value: '2', label: 'Kitchen 2' },
  { value: '3', label: 'Pantry' },
  { value: '4', label: 'Pantry 2' },
  { value: '5', label: 'Cellar' },
  { value: '6', label: 'Garage' },
  { value: '7', label: 'Other' },
];
export const drawerOptions = [
  { value: 'level', label: 'Where is it?' },
  { value: 'top', label: 'top' },
  { value: 'top left', label: 'top left' },
  { value: 'top middle', label: 'top middle' },
  { value: 'top right', label: 'top right' },
  { value: 'middle', label: 'middle' },
  { value: 'bottom', label: 'bottom' },
  { value: 'bottom left', label: 'bottom left' },
  { value: 'bottom middle', label: 'bottom middle' },
  { value: 'bottom right', label: 'bottom right' },
  { value: 'drawer top', label: 'drawer top' },
  { value: 'drawer 1', label: 'drawer 1' },
  { value: 'drawer 2', label: 'drawer 2' },
  { value: 'drawer middle', label: 'drawer middle' },
  { value: 'drawer 4', label: 'drawer 4' },
  { value: 'drawer bottom', label: 'drawer bottom' },
  { value: 'door', label: 'door' },
  { value: 'door top', label: 'door top' },
  { value: 'door middle', label: 'door middle' },
  { value: 'door buttom', label: 'door buttom' },
];
export const productOptions = [
  { value: 'what', label: 'What is it?' },
  { value: 'meat', label: 'Meat' },
  { value: 'fish', label: 'Fish' },
  { value: 'vegetables', label: 'Vegetables' },
  { value: 'fruits', label: 'Fruits' },
  { value: 'sweets', label: 'Sweets' },
  { value: 'mixedmeal', label: 'Mixed Meal' },
  { value: 'veggiemeal', label: 'Veggie Meal' },
  { value: 'veganmeal', label: 'Vegan Meal' },
  { value: 'bread', label: 'Bread' },
  { value: 'water', label: 'Water' },
  { value: 'icecream', label: 'Icecream' },
  { value: 'herbs', label: 'Herbs' },
  { value: 'liquor', label: 'Liquor' },
  { value: 'soup', label: 'Soup' },
  { value: 'other', label: 'Other' },
];
export const madeOptions = [
  { value: 'readyness', label: 'How prepared is it?' },
  { value: 'ready', label: 'Ready 2 (h)eat' },
  { value: 'halfready', label: 'Half prepared' },
  { value: 'raw', label: 'Raw' },
];
